In [1]:
import tensorflow as tf
import keras
from tensorflow.keras.layers import Input, Dense, Conv2D
from tensorflow.keras import Sequential
from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array, array_to_img
from tensorflow.keras.models import Model
from tensorflow.keras.layers import UpSampling2D, MaxPooling2D, Flatten
import cv2
import os
import random
from tqdm import tqdm
import numpy as np
from keras.preprocessing import image
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import concatenate
from tensorflow.keras.layers import BatchNormalization
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tensorflow.keras.applications.vgg19 import VGG19
from keras.applications.vgg19 import preprocess_input

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [46]:
vgg = VGG19(input_shape = (224,224,3), include_top=False, weights='imagenet')

In [47]:
model = Sequential()

In [48]:
for layers in vgg.layers:
    layers.trainable=False

In [49]:
for layers in vgg.layers:
    model.add(layers)

In [50]:
model.add(Flatten())
# model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(Dense(1, activation='sigmoid'))

In [51]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)      

In [8]:
gloves = []
count = 0
# names = []
# features = []
!pip install tqdm
from tqdm import tqdm
for file in os.listdir('/kaggle/input/augmented-gloves/augmented_gloves'):
    if file != 'Annotations':
#         for img in tqdm(os.listdir(os.path.join('/kaggle/input/face-mask-dataset/data', file))):

            image = load_img(os.path.join('/kaggle/input/augmented-gloves/augmented_gloves', file), target_size=(224, 224))
            img_array = img_to_array(image)
    #         img_array = img_array.reshape((1, img_array.shape[0], img_array.shape[1], img_array.shape[2]))
            img_array = preprocess_input(img_array)
    #         img_array /= 255.
    #         print(img)
            gloves.append((1, img_array))
            count+=1
#         names.append(img)

In [9]:
palms = []
count = 0
# names = []
# features = []
!pip install tqdm
from tqdm import tqdm
for file in os.listdir('/kaggle/input/augmented-palms/augmented_palms'):
#     if file != 'Annotations':
#         for img in tqdm(os.listdir(os.path.join('/kaggle/input/face-mask-dataset/data', file))):
    try:
        image = load_img(os.path.join('/kaggle/input/augmented-palms/augmented_palms', file), target_size=(224, 224))
        img_array = img_to_array(image)
#         img_array = img_array.reshape((1, img_array.shape[0], img_array.shape[1], img_array.shape[2]))
        img_array = preprocess_input(img_array)
#         img_array /= 255.
#         print(img)
        palms.append((0, img_array))
        count+=1
    except:
        pass
#         names.append(img)

In [10]:
test = []
count = 0
# names = []
# features = []
!pip install tqdm
from tqdm import tqdm
for file in os.listdir('/kaggle/input/test-data/test'):
#     if file != 'Annotations':
#         for img in tqdm(os.listdir(os.path.join('/kaggle/input/face-mask-dataset/data', file))):
    try:
        image = load_img(os.path.join('/kaggle/input/test-data/test', file), target_size=(224, 224))
        img_array = img_to_array(image)
#         img_array = img_array.reshape((1, img_array.shape[0], img_array.shape[1], img_array.shape[2]))
        img_array = preprocess_input(img_array)
#         img_array /= 255.
#         print(img)
        test.append((0, img_array))
        count+=1
    except:
        pass
#         names.append(img)

In [11]:
print(len(gloves))
print(len(palms))
print(len(test))

3600
4592
20


In [12]:
gloves[1]

(1,
 array([[[ 128.061   ,  129.22101 ,  129.32    ],
         [ 129.061   ,  132.22101 ,  128.32    ],
         [ 129.061   ,  131.22101 ,  128.32    ],
         ...,
         [  67.061   ,   80.221   ,   92.32    ],
         [  90.061   ,  100.221   ,  109.32    ],
         [ 101.061   ,  108.221   ,  112.32    ]],
 
        [[  83.061   ,   84.221   ,  100.32    ],
         [ 120.061   ,  122.221   ,  123.32    ],
         [ 124.061   ,  127.221   ,  127.32    ],
         ...,
         [  87.061   ,  100.221   ,  109.32    ],
         [ 108.061   ,  119.221   ,  124.32    ],
         [ 106.061   ,  118.221   ,  120.32    ]],
 
        [[  60.060997,   54.221   ,   88.32    ],
         [  72.061   ,   65.221   ,   95.32    ],
         [ 100.061   ,  100.221   ,  115.32    ],
         ...,
         [  99.061   ,  111.221   ,  113.32    ],
         [ 103.061   ,  116.221   ,  120.32    ],
         [ 104.061   ,  116.221   ,  119.32    ]],
 
        ...,
 
        [[  73.061   ,   99.22

In [13]:
data = []

for i in gloves:
    data.append(i)
    
for i in palms:
    data.append(i)

In [14]:
test_data = []

for i in test:
    test_data.append(i)


In [15]:
len(data)

8192

In [16]:
len(test_data)

20

In [17]:
data[0]

(1,
 array([[[ 2.7060997e+01,  7.8221001e+01,  4.2320000e+01],
         [ 3.1060997e+01,  8.0221001e+01,  4.6320000e+01],
         [ 3.7060997e+01,  8.5221001e+01,  5.3320000e+01],
         ...,
         [ 3.3060997e+01,  8.4221001e+01,  4.4320000e+01],
         [ 3.0060997e+01,  8.1221001e+01,  4.0320000e+01],
         [ 3.5060997e+01,  8.6221001e+01,  4.5320000e+01]],
 
        [[ 2.6060997e+01,  7.8221001e+01,  4.3320000e+01],
         [ 2.8060997e+01,  7.7221001e+01,  4.4320000e+01],
         [ 1.8060997e+01,  6.3221001e+01,  3.3320000e+01],
         ...,
         [ 3.7060997e+01,  8.8221001e+01,  4.7320000e+01],
         [ 3.2060997e+01,  8.4221001e+01,  4.3320000e+01],
         [ 3.5060997e+01,  8.6221001e+01,  4.5320000e+01]],
 
        [[ 2.8060997e+01,  7.9221001e+01,  4.6320000e+01],
         [ 2.2060997e+01,  7.0221001e+01,  3.9320000e+01],
         [-1.6939003e+01,  1.1221001e+01, -1.1680000e+01],
         ...,
         [ 3.4060997e+01,  8.5221001e+01,  4.4320000e+01],
    

In [18]:
test_data[0]

(0,
 array([[[ -43.939003,  -51.779   ,  -25.68    ],
         [ -43.939003,  -38.779   ,  -14.68    ],
         [ -46.939003,  -60.779   ,  -81.68    ],
         ...,
         [ -96.939   , -110.779   , -108.68    ],
         [ -91.939   , -103.779   , -112.68    ],
         [ -94.939   , -105.779   , -111.68    ]],
 
        [[ -34.939003,  -63.779   ,  -53.68    ],
         [  -7.939003,  -50.779   ,  -14.68    ],
         [ -14.939003,  -52.779   ,  -25.68    ],
         ...,
         [ -99.939   , -111.779   , -104.68    ],
         [ -81.939   ,  -93.779   , -104.68    ],
         [ -92.939   , -104.779   ,  -97.68    ]],
 
        [[ -44.939003,  -56.779   ,  -53.68    ],
         [ -61.939003,  -45.779   ,  -25.68    ],
         [ -33.939003,  -31.779   ,  -36.68    ],
         ...,
         [ -90.939   , -110.779   , -114.68    ],
         [ -91.939   , -110.779   ,  -98.68    ],
         [ -99.939   , -107.779   , -115.68    ]],
 
        ...,
 
        [[  -2.939003,  -49.77

In [19]:
import random
random.shuffle(data)
random.shuffle(test_data)

In [20]:
data[0]

(0,
 array([[[-30.939003 ,   6.2210007,  11.32     ],
         [-33.939003 ,   3.2210007,   8.32     ],
         [-34.939003 ,   2.2210007,   7.3199997],
         ...,
         [  5.060997 ,  39.221    ,  71.32     ],
         [  9.060997 ,  43.221    ,  74.32     ],
         [  8.060997 ,  40.221    ,  71.32     ]],
 
        [[-30.939003 ,   6.2210007,  11.32     ],
         [-31.939003 ,   5.2210007,  10.32     ],
         [-34.939003 ,   2.2210007,   7.3199997],
         ...,
         [  4.060997 ,  38.221    ,  69.32     ],
         [  9.060997 ,  43.221    ,  74.32     ],
         [  5.060997 ,  38.221    ,  69.32     ]],
 
        [[-30.939003 ,   6.2210007,  11.32     ],
         [-34.939003 ,   2.2210007,   7.3199997],
         [-35.939003 ,   1.2210007,   6.3199997],
         ...,
         [  8.060997 ,  43.221    ,  74.32     ],
         [  9.060997 ,  43.221    ,  74.32     ],
         [  2.060997 ,  34.221    ,  64.32     ]],
 
        ...,
 
        [[  8.060997 ,  44.221

In [21]:
new_data = []
features = []
# features = []
for i in data:
    new_data.append(i[1])
for i in data:
    features.append(i[0])
       
# for i in data:
#     new_data.append(i[1])

In [22]:
test_data[0]

(0,
 array([[[ -93.939    , -107.779    , -112.68     ],
         [ -91.939    , -102.779    , -108.68     ],
         [ -92.939    , -105.779    , -106.68     ],
         ...,
         [  23.060997 ,   34.221    ,   45.32     ],
         [ -48.939003 ,  -39.779    ,   31.32     ],
         [ -59.939003 ,  -52.779    ,   27.32     ]],
 
        [[ -95.939    , -106.779    , -112.68     ],
         [ -93.939    , -105.779    , -108.68     ],
         [ -94.939    , -106.779    , -109.68     ],
         ...,
         [  27.060997 ,   37.221    ,   52.32     ],
         [ -58.939003 ,  -48.779    ,   20.32     ],
         [ -39.939003 ,  -28.779    ,   40.32     ]],
 
        [[ -91.939    , -104.779    , -105.68     ],
         [ -94.939    , -106.779    , -109.68     ],
         [ -92.939    , -105.779    , -106.68     ],
         ...,
         [   7.060997 ,   10.221001 ,   46.32     ],
         [ -48.939003 ,  -36.779    ,   28.32     ],
         [ -47.939003 ,  -35.779    ,   29.32  

In [23]:
new_data_test = []
features_test = []
# features = []
for i in test_data:
    new_data_test.append(i[1])
    
for i in test_data:
    features_test.append(i[0])

In [24]:
len(new_data)

8192

In [25]:
len(new_data_test)

20

In [26]:
new_data[0]

array([[[-30.939003 ,   6.2210007,  11.32     ],
        [-33.939003 ,   3.2210007,   8.32     ],
        [-34.939003 ,   2.2210007,   7.3199997],
        ...,
        [  5.060997 ,  39.221    ,  71.32     ],
        [  9.060997 ,  43.221    ,  74.32     ],
        [  8.060997 ,  40.221    ,  71.32     ]],

       [[-30.939003 ,   6.2210007,  11.32     ],
        [-31.939003 ,   5.2210007,  10.32     ],
        [-34.939003 ,   2.2210007,   7.3199997],
        ...,
        [  4.060997 ,  38.221    ,  69.32     ],
        [  9.060997 ,  43.221    ,  74.32     ],
        [  5.060997 ,  38.221    ,  69.32     ]],

       [[-30.939003 ,   6.2210007,  11.32     ],
        [-34.939003 ,   2.2210007,   7.3199997],
        [-35.939003 ,   1.2210007,   6.3199997],
        ...,
        [  8.060997 ,  43.221    ,  74.32     ],
        [  9.060997 ,  43.221    ,  74.32     ],
        [  2.060997 ,  34.221    ,  64.32     ]],

       ...,

       [[  8.060997 ,  44.221    ,  51.32     ],
        [ 1

In [27]:
# names

In [28]:
# label

In [29]:
features

[0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,


In [30]:
# features.sort(reverse=True)

In [31]:
features = np.array(features)
new_data = np.array(new_data)
features_test = np.array(features_test)
new_data_test = np.array(new_data_test)

In [32]:
from tensorflow.keras.callbacks import EarlyStopping

In [40]:
callback = EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=2,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False
)

In [41]:
# features

In [42]:
len(features_test)

20

In [43]:
features_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])

In [54]:
model.fit(new_data, features, epochs=50, validation_split=0.2, callbacks=callback, shuffle=True)

Epoch 1/50
205/205 [==============================] - 48s 229ms/step - loss: 0.1834 - acc: 0.9303 - val_loss: 0.0834 - val_acc: 0.9664
Epoch 2/50
205/205 [==============================] - 43s 212ms/step - loss: 0.0371 - acc: 0.9852 - val_loss: 0.0623 - val_acc: 0.9762
Epoch 3/50
205/205 [==============================] - 44s 215ms/step - loss: 0.0278 - acc: 0.9898 - val_loss: 0.0704 - val_acc: 0.9762
Epoch 4/50
205/205 [==============================] - 44s 214ms/step - loss: 0.0223 - acc: 0.9916 - val_loss: 0.0653 - val_acc: 0.9762
Epoch 4: early stopping


In [56]:
model.save('gloves_detector-2.keras')